---
name: Debug arbitrary commands
on:
  push:
    paths: .github/workflows/debug_arbitrary_commands.yml
jobs:
  debug_other_workflow:
    uses: ./.github/workflows/debug_context.yml
    with:
      environment: ${{ github.event.inputs.my_env }}
      noop: false
      arbitrary: whatever
      other_param: 'fooooo'
      run: |
        env
        echo "Hello world"
  debug_other_composite_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Drowze/ci-testing/action-arbitrary-run-command@master
        with:
          run: |
            env
            echo "Hello world"
  debug_stderr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            let exitCode
            let stdout
            let stderr
            let {
              exitCode,
              stdout,
              stderr
            } = await exec.getExecOutput('ruby', ['-e', '$stderr.puts "something went wrong\nlololol\nmultiline!!!" ; exit 3']);
            if(exitCode != 0) {
              core.error(stderr)
              exit exitCode
            } else {
              console.info("exec was successful")
            }
